#
# 超级对抗赛决策配置文件
#
navigation:
  map_yaml: maps/rmuc.yaml

decision:
  health_limit: 150
  health_ready: 350
  bullet_limit: 0
  bullet_ready: 0
  home: [1.2, 6.3]

  cruise_methods:
    # 侵略性的巡航策略，压家
    aggressive:
      - [6.0, 4.0]
      - [7.5, 6.0]
      - [9.5, 7.0]
      - [11.0, 7.0]
    # 以占领为主的策略，在中心占据区巡航
    occupation:
      - [5.0, 3.0]
      - [7.0, 3.0]
      - [5.0, 5.0]
      - [7.0, 5.0]
