#
# 联盟赛决策配置文件
#
navigation:
  map_yaml: maps/rmul.yaml

decision:
  health_limit: 250
  health_ready: 350
  bullet_limit: 0
  bullet_ready: 0
  home: [1.2, 6.3]

  # 巡航时间间隔，单位为 s
  cruise_interval: 5
  cruise_methods:
    # 侵略性的巡航策略，压家
    aggressive:
      - [6.0, 4.0]
      - [7.5, 6.0]
      - [9.5, 7.0]
      - [11.0, 7.0]
    # 以占领为主的策略，在中心占据区巡航
    # 中心点为 (6.0, 4.0)
    occupation:
      - [5.5, 3.5]
      - [6.5, 3.5]
      - [5.5, 4.5]
      - [6.5, 4.5]
